### ISSUE TITLE
simple search

### ISSUE THREAD

**Issue by kiloki-official** [typesense/typesense-dart#111]
Can you please explain how I can make a simple search on one of my collections? I followed the typesense tutorials but I can't get anything to work with your package. Thanks

**Comment by kiloki-official** [comment]
Ignore my previous message. I found out how to do a search using your package. Thanks

**Comment by happy-san** [comment]
Hey @kiloki-official! Glad to know you got the search working. If you're looking for working examples, check out the `example/console-simple` directory.
