### ISSUE TITLE
Valid `x-typesense-api-key` header must be sent

### ISSUE THREAD

**Issue by elhe26** [typesense/typesense-dart#115]
### Describe the bug
It seems the Configuration object is not setting the API key.  Basic configuration:

```dart
class SearchService {
Client? client;
String searchOne = "add-endpoint-here";
String searchTwo = "add-endpoint-here";
String searchThree = "add-endpoint-here";

void initialize(String searchKey) {
    var config = Configuration(
      searchKey,
      nodes: {
        Node(Protocol.https, searchOne, port: 443),
        Node(Protocol.https, searchTwo, port: 443),
        Node(Protocol.https, searchThree, port: 443),
        },
      connectionTimeout: Duration(seconds: 2),
      );
      client = Client(config);
   }

  Future<dynamic> Search(
    String? value,
    String queryBy,
    String collection,
  ) async {
    try {
      var search = await client!.collection(collection).documents.search({
        "q": value ?? "*",
        "query_by": queryBy,
      });
         return search;
        } catch(err){
          return err;
        }
    }
}
```

Related: [Typesense Error 476](https://github.com/typesense/typesense/issues/476)

### Steps to reproduce the behavior:
1. Initialize client - **No issues**
2. Search/retrieve documents - **Error**

### Expected behavior
1 . Return either collections or documents. 

### Additional context
- Using a shell to query/retrieve any document doesn't cause any issue. 
- Using Admin-Key, Search-only-Key, and Scoped-Key cause the same errors.
- Using client SDK:

***Error 1***
```bash
401: {"message": "Forbidden - a valid `x-typesense-api-key` header must be sent."}
```

***Error 2***
This error is also a weird behavior from the client SDK.  All schema variables are defined with type and facet. If the client is not throwing Error 1, it's giving this other error:

```bash
400: {"message": "Field `value` should be a string or a string array."}
```

"value" variable config (Schema):
```bash
...
    {
      "facet": false,
      "index": true,
      "name": "value",
      "optional": false,
      "type": "float"
    },
...
```

*Note:*
Setting the "sendApiKeyAsQueryParam" variable won't change the outcome.

**Comment by elhe26** [comment]
### **Update:**

Searching, retrievals, etc... using dart's HTTP library generates no issues.

Admin Key & Scoped Search Keys are working without any inconveniences atm.

**Comment by happy-san** [comment]
Hey @elhe26 
Can you clarify if you're facing `401` error using the same key with shell and SDK?

>Using a shell to query/retrieve any document doesn't cause any issue.
Using Admin-Key, Search-only-Key, and Scoped-Key cause the same errors.

Also, have you used the dart SDK to generate the search key?

**Comment by happy-san** [comment]
Regarding Error 2,
I suggest creating a separate issue. Also, it would be helpful if you'd include the response of [collections/{collection_name}](https://typesense.org/docs/0.22.1/api/collections.html#retrieve-a-collection).

**Comment by elhe26** [comment]
> Hey @elhe26 Can you clarify if you're facing `401` error using the same key with shell and SDK?
> 
> > Using a shell to query/retrieve any document doesn't cause any issue.
> > Using Admin-Key, Search-only-Key, and Scoped-Key cause the same errors.
> 
> Also, have you used the dart SDK to generate the search key?

I created the key from the server using typesense-js. When using the scoped key from the shell, I don't get any issues. When using it from the client I get that error.

**Comment by happy-san** [comment]
>I created the key from the server using typesense-js.

I'm assuming you're referring to creating a scoped search key here?

**Comment by elhe26** [comment]
> >I created the key from the server using typesense-js.
> 
> I'm assuming you're referring to creating a scoped search key here?

Yes. I used the admin key to create a search-only key and then I generated the scoped key.

**Comment by happy-san** [comment]
@elhe26 I tried to reproduce the issue with the following code and found nothing.

```dart
void main(List<String> arguments) async {
  /// Initial search key generated by the typesense cluster.
  final searchKey = 'SSw1XmjxjjcA2Raq0UhNPgPff7XTLbF7';
  final config = Configuration(
    searchKey,
    nodes: {
      Node(
        Protocol.https,
        'Host',
      ),
    },
  );

  final client = Client(config);

  // Generate scoped search key
  final scopedSearchKey = client.keys.generateScopedSearchKey(
    'SSw1XmjxjjcA2Raq0UhNPgPff7XTLbF7',
    {
      'query_by': 'company_name',
      'filter_by': 'country:=abc && num_employees:>0',
    },
  );

  print(scopedSearchKey);

  final configuration = Configuration(
    scopedSearchKey,
    nodes: {
      Node(
        Protocol.https,
        'pawifkv7boh6dzc8p-1.a1.typesense.net',
      ),
    },
  );

  final clientWithScopedSearchKey = Client(configuration);
  print(
    await clientWithScopedSearchKey.collection('companies').documents.search(
      {
        'q': '',
      },
    ),
  );
}
```

I believe you're trying to perform an action that's out of the scope of the key. Using the admin key try [retrieve](https://typesense.org/docs/0.22.2/api/api-keys.html#retrieve-an-api-key) and look for the permissions of the key you're using.

**Comment by happy-san** [comment]
@elhe26 I tried to reproduce the issue with the following code and found nothing.

```dart
void main(List<String> arguments) async {
  /// Initial search key generated by the typesense cluster.
  final searchKey = 'SSw1XmjxjjcA2Raq0UhNPgPff7XTLbF7';
  final config = Configuration(
    searchKey,
    nodes: {
      Node(
        Protocol.https,
        'Host',
      ),
    },
  );

  final client = Client(config);

  // Generate scoped search key
  final scopedSearchKey = client.keys.generateScopedSearchKey(
    'SSw1XmjxjjcA2Raq0UhNPgPff7XTLbF7',
    {
      'query_by': 'company_name',
      'filter_by': 'country:=abc && num_employees:>0',
    },
  );

  print(scopedSearchKey);

  final configuration = Configuration(
    scopedSearchKey,
    nodes: {
      Node(
        Protocol.https,
        'Host',
      ),
    },
  );

  final clientWithScopedSearchKey = Client(configuration);
  print(
    await clientWithScopedSearchKey.collection('companies').documents.search(
      {
        'q': '',
      },
    ),
  );
}
```

I believe you're trying to perform an action that's out of the scope of the key. Using the admin key try [retrieve](https://typesense.org/docs/0.22.2/api/api-keys.html#retrieve-an-api-key) and look for the permissions of the key you're using.

**Comment by elhe26** [comment]
Thanks @happy-san. I'm following the docs but I'm getting the same issue. I'll start over again and see if that works.

**Comment by happy-san** [comment]
For future reference, try to log your exact steps.
