### ISSUE TITLE
Implementing documents API endpoint

### ISSUE THREAD

**Issue by HarisaranG** [typesense/typesense-dart#12]
## Description

Will implement documents API endpoint along with unit tests.

**Comment by HarisaranG** [comment]
@happy-san In API call class body parameters for post function is `Map<String, String>` but documents can have `Map<String, dynamic`. I will make the required changes in ApiCall class

**Comment by happy-san** [comment]
@HarisaranG I was thinking to change it to `Object` similar to `put` function. But I guess if `Map<String, dynamic>` does it, for now, it's better.

**Comment by HarisaranG** [comment]
@happy-san For performing `import` in documents endpoint jsonl string format documents are required. So I need to perform request directly with `_requestCore` and `_requestUri` which are private members what should I do now ?

**Comment by happy-san** [comment]
Are you referring to [this](https://github.com/typesense/typesense-js/blob/59c7bba882f878f54b786e95a3242bc8c5e6a7b5/src/Typesense/Documents.js#L43)?

**Comment by happy-san** [comment]
Also, I've added [`CONTENT_TYPE`](https://github.com/typesense/typesense-dart/blob/44b9364152baba6a99a8322e5b0a01a19c0ba9cd/lib/src/api_call.dart#L14) constant to `ApiCall`. You can use it like:

```dart
apiCall.post( 'endpoint',
  additionalHeaders: {ApiCall.CONTENT_TYPE: 'text/plain'},
);
```

**Comment by HarisaranG** [comment]
> Are you referring to [this](https://github.com/typesense/typesense-js/blob/59c7bba882f878f54b786e95a3242bc8c5e6a7b5/src/Typesense/Documents.js#L43)?
> 
> If yes, then you simply need to update the `post` function's [body](https://github.com/typesense/typesense-dart/blob/e4b107effe87004ab8e201d2e63ddf21b31caae7/lib/src/api_call.dart#L69) parameter to `Object` and then `apiCall.post()` would accomplish what [this](https://github.com/typesense/typesense-js/blob/master/src/Typesense/Documents.js#L51-#L59) code is accomplishing.

Like the import function takes `String` as a body parameter. But the `post` function has `Map<String, dynamic>`.  So now can I change `Map<String, dynamic>` to `dynamic` or change `_requestCore` and `_requestUri` to public functions and make the post request using it?

**Comment by happy-san** [comment]
@HarisaranG You can fetch the latest commit from the master repo, I've made the changes required for you to implement the import function.

**Comment by HarisaranG** [comment]
@happy-san Yeah now I am able to call the post function.
Check this out: [Document Import Response](https://typesense.org/docs/0.20.0/api/documents.html#sample-response-9)
```js
{"success": true}
{"success": true}
{"success": true}
```
But the response is also a `String` of jsonl. But the post function return `Map<String, dynamic>`.

**Comment by happy-san** [comment]
@HarisaranG Could you open a PR with what you've done so far? Then we can brainstorm on this together.

**Comment by HarisaranG** [comment]
Yeah sure on it !

**Comment by happy-san** [comment]
@HarisaranG Checkout this:

```dart
import 'dart:convert';

void main() {
  final jsonl = """
  {"first": 1}
  {"second": 2}
  {"third": 3}""", encoded = json.encode(jsonl), decoded = json.decode(encoded);
  
  print('$jsonl\n');
  print('$encoded\n');
  print('$decoded\n');
  print(json.decode(jsonl)); // This throws format exception
}
```
Indeed `_handleNodeResponse` would freak out if jsonl is returned from the server.

**Comment by happy-san** [comment]
> Even json.decode(response.body) would fail passing the jsonl string
Do you have any suggestions on how this could be avoided? I don't have any good solutions atm.

**Comment by happy-san** [comment]
The best way I think to handle this situation is to decouple the node pooling logic and the request/response logic of the `ApiCall` class. Then there can be multiple implementations with custom request/response but a single node pool.

Something like this:

```dart
abstract class BaseApiCall<R> {
  final Configuration _config;
  
  BaseApiCall(Configuration config) : _config = config;
  
  Future<R> sendRequest(Future<http.Response> Function(Node) predicate) async {
    http.Response response;
    for (var triesLeft = _config.numRetries;;) {
      final node = NodePool.nextNode();
      try {
        response = await predicate(node).timeout(
          _config.connectionTimeout,
        );
        return handleNodeResponse(node, response);
      } catch (e) {
        if (--triesLeft <= 0) {
          // We've exhausted our tries, rethrow.
          rethrow;
        }

        if (e is RequestException && response.statusCode < 500) {
          // If response is anything but 5xx, rethrow.
          rethrow;
        } else {
          // Retry all other HTTP errors (HTTPStatus > 500) after [retryInterval].
          await Future.delayed(_config.retryInterval);
        }
      }
    }
  }
  
  Future<R> handleNodeResponse(Node node, http.Response response);
}
```

**Comment by HarisaranG** [comment]
> Do you have any suggestions on how this could be avoided? I don't have any good solutions atm.

Having statically typed data types is good, but we could change variables to `dynamic`  types for this case. So that even updating the client on the coming up version would be easier I guess

**Comment by happy-san** [comment]
Which variables are you referring to specifically?

**Comment by HarisaranG** [comment]
@happy-san 
I was looking into `api_call.dart` primarily we need to change for `_handleNodeResponse`. Then, it will be a chain reaction to change in all functions.

Or a workaround way would be creating a new public function for this case in `ApiCall` but this would very difficult for the client updates

**Comment by happy-san** [comment]
> Or a workaround way would be creating a new public function for this case in ApiCall but this would very difficult for the client updates

Exactly why I am looking to create an abstraction such that any request/response type can be implemented without any conflict with existing ones. I'll update you regarding this by tomorrow. 

P.S. Make sure your PR branch has the latest changes from the master. Currently it's in conflict.

**Comment by HarisaranG** [comment]
> P.S. Make sure your PR branch has the latest changes from the master. Currently, it's in conflict.

Oh really ?. It is in line with the master branch only but I have updated it with some changes for the `post` function alone in `ApiCall`,

```dart
Future<Map<String, dynamic>> post(
    String endpoint, {
    Map<String, dynamic> queryParams = const {},
    Map<String, dynamic> additionalHeaders = const {},
    Object bodyParameters,
  }) 
```
Because queryParams could be a integer also

**Comment by happy-san** [comment]
Oh, I was looking to rebase your PR into master, it can be merged instead. Nothing to worry about, my bad.

**Comment by HarisaranG** [comment]
Awesome! Waiting for your update ⌛
