### ISSUE TITLE
Add ability to specify locale when creating a schema

### ISSUE THREAD

**Issue by keith555** [typesense/typesense-dart#120]
I can assign a locale to a schema field using the API directly, like this

```
	 curl "http://localhost:8108/collections" \
       -X POST \
       -H "Content-Type: application/json" \
       -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
       -d '{
         "name": "english_thai",
         "fields": [
          {"name": "english", "type": "string" },
          {"name": "thai", "type": "string", "locale": "th" }
         ],
         "default_sorting_field": "num_employees"
       }'
```

I can't find an equivalent way to specify locale using the dart client.

**Comment by keith555** [comment]
> 

2.17.0 is fine. Thanks a lot for your quick response.

**Comment by happy-san** [comment]
Hi @keith555 
Could you check out this branch?
https://github.com/happy-san/typesense-dart/blob/chores/lib/src/models/field.dart

There are some breaking changes to the models to support the v0.23.0 Typsense. I hope that's acceptable.

**Comment by keith555** [comment]
That seems to be working now. Thanks a lot for your speedy help.
