### ISSUE TITLE
Update pub.dev version

### ISSUE THREAD

**Issue by otopba** [typesense/typesense-dart#124]
Hey, 

Could you please update version at pub.dev?
I need last changes from master branch

Thanks

**Comment by happy-san** [comment]
Hi @otopba, you can update your `pubspec.yaml` like this for now

```dart
  typesense-dart:
    git:
      url: git://github.com/typesense/typesense-dart.git
```

**Comment by happy-san** [comment]
`typesense: ^0.3.0` is now published on pub.
