### ISSUE TITLE
preset appears to be ignored in request from Dart

### ISSUE THREAD

**Issue by jordan112** [typesense/typesense-dart#136]
The presets passed in don't seem to work.  I get an error stating i need to add query parameters, when i thought that the preset would be the only thing I need.

### Steps to reproduce the behavior:
1.  Generate a search query
2.  don't add query params only use reset
3. get error stating no query params were declared

### Expected behavior
It should be able to only use the preset without specifying query or sort parameters, so preset can be managed from Typesense cloud and not update client

### Screenshots
None

### Additional context
```
 final searchParameters = {
      'q': searchKey, // Access searchKey property using the null-aware operator
      'per_page': pageSize.toString(),
      'page': (pageKey + 1).toString(),
      'preset': 'inventory_search',
      'query_by':
          'category,notes,origin,status,title,listingPlatforms,soldPlatform',
      'filter_by': filterBy,
      "sort_by": sortString,
      "facet_by": "category,status",
    };
```

**Comment by happy-san** [comment]
Hello @jordan112 Could you also share the preset definition?

**Comment by happy-san** [comment]
I tried to create to create the following preset and it worked fine for me.
```dart
  await client.presets.upsert('query_field_preset', {
    'value': {
      'query_by': 'company_name',
    }
  });

  await client.collection('companies').documents.search(
    {
      'q': 'Corp',
      'preset': 'country_filter_preset',
      'filter_by': 'country:=USA',
    },
  );
```

**Comment by jordan112** [comment]
This appears to be working now.  At one point while implementing, i got errors stating query parameters were required even though i had a preset.  closing this issue.  

Here is my preset for reference

<img width="763" alt="image" src="https://github.com/typesense/typesense-dart/assets/630479/79f08d72-7bb6-4563-93e9-668dc767e56a">
