### ISSUE TITLE
Do you know why I cannot connect to my typesense docker container?

### ISSUE THREAD

**Issue by ember11498** [typesense/typesense-dart#137]
So my code looks like that. The host is the IP of my droplet from digital ocean (the ip is made up). When I check the health of my typesense docker in the shell of my droplet i get {"ok":true}. So since typesense is installed fine i guess i must be doing something wrong in this part of the code. When i try to connect it always timeouts. Any ideas?

      Client init() {
        final config = Configuration(
          'xyz',
          nodes: {
            Node.withUri(
              Uri(
                scheme: 'http',
                host: '178.127.255.241',
                port: 8108,
              ),
            ),
          },
          numRetries: 3, // A total of 4 tries (1 original try + 3 retries)
          connectionTimeout: const Duration(seconds: 15),
        );
        final client = Client(config);
        return client;
      }

**Comment by ember11498** [comment]
an excerpt of my portainer logs regarding the typesense container:

  I20240115 18:25:41.959857   107 raft_server.h:60] Peer refresh succeeded!
  I20240115 18:25:51.961141    91 raft_server.cpp:557] Term: 4, pending_queue: 0, last_index: 3, committed: 3, known_applied: 3, applying: 0, pending_writes: 0, queued_writes: 0, local_sequence: 3
  I20240115 18:25:51.961241   107 raft_server.h:60] Peer refresh succeeded!
  I20240115 18:26:01.962700    91 raft_server.cpp:557] Term: 4, pending_queue: 0, last_index: 3, committed: 3, known_applied: 3, applying: 0, pending_writes: 0, queued_writes: 0, local_sequence: 3
  I20240115 18:26:01.963039   107 raft_server.h:60] Peer refresh succeeded!
  I20240115 18:26:11.964304    91 raft_server.cpp:557] Term: 4, pending_queue: 0, last_index: 3, committed: 3, known_applied: 3, applying: 0, pending_writes: 0, queued_writes: 0, local_sequence: 3
  I20240115 18:26:11.964612   107 raft_server.h:60] Peer refresh succeeded!
  I20240115 18:26:21.966152    91 raft_server.cpp:557] Term: 4, pending_queue: 0, last_index: 3, committed: 3, known_applied: 3, applying: 0, pending_writes: 0, queued_writes: 0, local_sequence: 3
  I20240115 18:26:21.966281   107 raft_server.h:60] Peer refresh succeeded!
  I20240115 18:26:26.875175    92 batched_indexer.cpp:288] Running GC for aborted requests, req map size: 0
  I20240115 18:26:31.967540    91 raft_server.cpp:557] Term: 4, pending_queue: 0, last_index: 3, committed: 3, known_applied: 3, applying: 0, pending_writes: 0, queued_writes: 0, local_sequence: 3
  I20240115 18:26:31.967646   107 raft_server.h:60] Peer refresh succeeded!

**Comment by ember11498** [comment]
an excerpt of my portainer logs right when I initialize my typesense docker container

`
    I20240115 18:40:33.131739     1 typesense_server_utils.cpp:334] Starting Typesense 0.25.2
    I20240115 18:40:33.132076     1 typesense_server_utils.cpp:337] Typesense is using jemalloc.
    I20240115 18:40:33.132412     1 typesense_server_utils.cpp:387] Thread pool size: 8
    I20240115 18:40:33.134585     1 store.h:64] Initializing DB by opening state dir: /data/db
    I20240115 18:40:33.155617     1 store.h:64] Initializing DB by opening state dir: /data/meta
    I20240115 18:40:33.178138     1 ratelimit_manager.cpp:546] Loaded 0 rate limit rules.
    I20240115 18:40:33.178392     1 ratelimit_manager.cpp:547] Loaded 0 rate limit bans.
    I20240115 18:40:33.179021     1 typesense_server_utils.cpp:507] Starting API service...
    I20240115 18:40:33.179412     1 http_server.cpp:178] Typesense has started listening on port 8108
    I20240115 18:40:33.179751    91 typesense_server_utils.cpp:235] Since no --nodes argument is provided, starting a single node Typesense cluster.
    I20240115 18:40:33.180228    92 batched_indexer.cpp:124] Starting batch indexer with 8 threads.
    I20240115 18:40:33.180944    92 batched_indexer.cpp:129] BatchedIndexer skip_index: -9999
    I20240115 18:40:33.192430    91 server.cpp:1107] Server[braft::RaftStatImpl+braft::FileServiceImpl+braft::RaftServiceImpl+braft::CliServiceImpl] is serving on port=8107.
    I20240115 18:40:33.192613    91 server.cpp:1110] Check out http://f208ad57c52f:8107 in web browser.
    I20240115 18:40:33.193395    91 raft_server.cpp:68] Nodes configuration: 172.18.0.7:8107:8108
    I20240115 18:40:33.194535    91 log.cpp:690] Use murmurhash32 as the checksum type of appending entries
    I20240115 18:40:33.194751    91 log.cpp:1172] log load_meta /data/state/log/log_meta first_log_index: 1 time: 85
    I20240115 18:40:33.194834    91 log.cpp:1112] load open segment, path: /data/state/log first_index: 1
    I20240115 18:40:33.195582   111 raft_server.cpp:522] on_snapshot_load
    I20240115 18:40:33.196844   111 store.h:299] rm /data/db success
    I20240115 18:40:33.197260   111 store.h:309] copy snapshot /data/state/snapshot/snapshot_00000000000000000001/db_snapshot to /data/db success
    I20240115 18:40:33.197332   111 store.h:64] Initializing DB by opening state dir: /data/db
    I20240115 18:40:33.211472   111 store.h:323] DB open success!
    I20240115 18:40:33.211653   111 raft_server.cpp:501] Loading collections from disk...
    I20240115 18:40:33.211740   111 collection_manager.cpp:187] CollectionManager::load()
    I20240115 18:40:33.211860   111 auth_manager.cpp:34] Indexing 0 API key(s) found on disk.
    I20240115 18:40:33.211910   111 collection_manager.cpp:207] Loading upto 4 collections in parallel, 1000 documents at a time.
    I20240115 18:40:33.211949   111 collection_manager.cpp:216] Found 0 collection(s) on disk.
    I20240115 18:40:33.212168   111 collection_manager.cpp:316] Loaded 0 collection(s).
    I20240115 18:40:33.212327   111 collection_manager.cpp:320] Initializing batched indexer from snapshot state...
    I20240115 18:40:33.212400   111 batched_indexer.cpp:471] Restored 0 in-flight requests from snapshot.
    I20240115 18:40:33.212647   111 raft_server.cpp:508] Finished loading collections from disk.
    I20240115 18:40:33.212721   111 raft_server.h:285] Configuration of this group is 172.17.0.3:8107:8108
    I20240115 18:40:33.212837   111 snapshot_executor.cpp:264] node default_group:172.18.0.7:8107:8108 snapshot_load_done, last_included_index: 1 last_included_term: 2 peers: "172.17.0.3:8107:8108"
    I20240115 18:40:33.213071    91 raft_meta.cpp:521] Loaded single stable meta, path /data/state/meta term 4 votedfor 172.18.0.7:8107:8108 time: 32
    I20240115 18:40:33.213156    91 node.cpp:608] node default_group:172.18.0.7:8107:8108 init, term: 4 last_log_id: (index=3,term=4) conf: 172.18.0.7:8107:8108 old_conf: 
    I20240115 18:40:33.213279    91 node.cpp:1645] node default_group:172.18.0.7:8107:8108 term 4 start vote and grant vote self
    I20240115 18:40:33.215485    91 raft_meta.cpp:546] Saved single stable meta, path /data/state/meta term 5 votedfor 172.18.0.7:8107:8108 time: 1969
    I20240115 18:40:33.215662    91 node.cpp:1899] node default_group:172.18.0.7:8107:8108 term 5 become leader of group 172.18.0.7:8107:8108 
    I20240115 18:40:33.215811    91 raft_server.cpp:134] Node last_index: 3
    I20240115 18:40:33.215989    91 typesense_server_utils.cpp:283] Typesense peering service is running on 172.18.0.7:8107
    I20240115 18:40:33.216050    91 typesense_server_utils.cpp:284] Snapshot interval configured as: 3600s
    I20240115 18:40:33.216086    91 typesense_server_utils.cpp:285] Snapshot max byte count configured as: 4194304
    W20240115 18:40:33.216145    91 controller.cpp:1487] SIGINT was installed with 1
    I20240115 18:40:33.216288    91 raft_server.cpp:557] Term: 5, pending_queue: 1, last_index: 4, committed: 0, known_applied: 1, applying: 0, pending_writes: 0, queued_writes: 0, local_sequence: 1
    W20240115 18:40:33.216344    91 node.cpp:843] [default_group:172.18.0.7:8107:8108 ] Refusing concurrent configuration changing
    E20240115 18:40:33.216423   111 raft_server.h:62] Peer refresh failed, error: Doing another configuration change
    I20240115 18:40:33.217483   110 raft_server.h:285] Configuration of this group is 172.18.0.7:8107:8108
    I20240115 18:40:33.217957   110 raft_server.h:285] Configuration of this group is 172.18.0.7:8107:8108
    I20240115 18:40:33.218056   110 node.cpp:3298] node default_group:172.18.0.7:8107:8108 reset ConfigurationCtx, new_peers: 172.18.0.7:8107:8108, old_peers: 172.18.0.7:8107:8108
    I20240115 18:40:33.218149   110 raft_server.h:268] Node becomes leader, term: 5
    I20240115 18:40:43.217739    91 raft_server.cpp:557] Term: 5, pending_queue: 0, last_index: 4, committed: 4, known_applied: 4, applying: 0, pending_writes: 0, queued_writes: 0, local_sequence: 3
    I20240115 18:40:43.217861   104 raft_server.h:60] Peer refresh succeeded!
`

**Comment by jasonbosco** [comment]
I don't see any issues in the Typesense logs. This is a networking issue outside of Typesense. 

I'm not too familiar with portainer. So might be best to ask in their support forums on best practices to expose an http service (like Typesense) to the outside world.

Alternatively, you could install the DEB / RPM packages directly.

**Comment by ember11498** [comment]
@jasonbosco Thank you for the fast response. I guess the error must be in my dart code. In the host parameter I should place the IP of the droplet right?

**Comment by ember11498** [comment]
@jasonbosco I am sorry! it is working now 100%. I had set firewall rules on my droplet months and monrhts ago to block all ports except a few ones. i just added 8108 and now its working just fine. thank you!
