### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by happy-san** [typesense/typesense-dart#27]

**Comment by happy-san** [comment]
@jasonbosco I am looking for some suggestions:

`client.aliases('companies').retrieve()` v/s `client.aliases.retrieve('companies')`  [link](https://github.com/typesense/typesense-dart/pull/28/files#diff-2a4501187e92bf37187d4c6124bc9cdb3a8da9e88d86ffc41d5d4859f6c700daR55)

similarly,
`client.aliases('companies').delete()` v/s `client.aliases.delete('companies')`  [link](https://github.com/typesense/typesense-dart/pull/28/files#diff-2a4501187e92bf37187d4c6124bc9cdb3a8da9e88d86ffc41d5d4859f6c700daR44)

**Comment by jasonbosco** [comment]
@happy-san In other libraries, I've kept it as: `client.aliases('companies').retrieve()` and `client.aliases('companies').delete()`. So would be great to keep it consistent.

**Comment by happy-san** [comment]
As we discussed, I'll be following the convention that `typesense-go` is [using](https://github.com/typesense/typesense-go#retrieve-an-alias).
